image: fedora:latest

variables:
  DEPENDENCIES: desktop-file-utils
                gettext
                gcc-c++
                gtkmm4.0-devel
                itstool
                libadwaita-devel
                libsecret-devel
                libuuid-devel
                libxml2-devel
                libxslt-devel
                meson
                pcre-devel
                yelp-tools

  GIT_SUBMODULE_STRATEGY: normal

build:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson _build
    - meson test -C _build
    - ninja -C _build install
